### ISSUE TITLE
Invalid hook call. Hooks can only be called inside of the body of a function component

### ISSUE THREAD

**Issue by willscottrod** [OnedocLabs/react-print-pdf#40]
I'm trying to use this library to generate a static HTML file with tailwind CSS. Everything works up until I try using recharts. On your website, it looks like I can use it but I get issues once I try import a component and get the error:

Invalid hook call. Hooks can only be called inside of the body of a function component.

Is there a workaround to this or is this an unsupported function?

**Comment by Titou325** [comment]
Hey @willscottrod, thanks for reaching out! There are some incompatibilities with Recharts depending on your runtime. However templates such as the report and energy report use Recharts without issue. Can you provide more info on where you run the app (Vercel?), and share a snippet we can try? 

Thanks!

**Comment by willscottrod** [comment]
Hey @Titou325 

Apologies for getting back to you so late. It turns out it was just an issue with recharts and react hook table.  Weirdly, if the graphs weren't present, React hook table worked fine and visa versa. 

I didn't have the time to debug this further but to fix this, I just had to render the table statically (without react hook table)  to print it out with the graphs with a table.

**Comment by Titou325** [comment]
Thanks Will, let me know if you have a sample we should take a look at, will close this in the meantime :)
